name: Crash report
description: Submit a crash report
labels: ["crash"]
body:
    - type: textarea
      attributes:
          label: "Crash Information:"
          description: >
              Give a clear description of what happened and how to reproduce it, if possible. If you aren't sure, attempt to run the program through a debugger, such as [Valgrind](https://valgrind.org/) or enabling [faultview](https://docs.python.org/3/library/faultview.html).

              This should only be for *crashes* not bugs. For that, use the bug template.

          value: |
              ```py
              # Add your code here, if needed
              ```
      validations:
          required: true
    - type: input
      attributes:
          label: "Version:"
          value: |
              What version(s) of view.py are you using?
      validations:
          required: true
    - type: dropdown
      attributes:
          label: "Operating system(s) tested on:"
          multiple: true
          options:
              - Linux
              - macOS
              - Windows
              - Other
      validations:
          required: false
